# Only for development

services:
  django:
    depends_on:
      - postgresql
    build:
      target: prod
    command: python3 manage.py runserver 0.0.0.0:8080
    environment:
      PYTHONUNBUFFERED: 1
      ANDREW_HOST_NAME: localhost
      DJANGO_DEBUG: True
      DJANGO_LOG_LEVEL: DEBUG
      DJANGO_SECRET_KEY: 123456
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: andrew
      POSTGRES_DB: andrew
      ANDREW_DJANGO_ADMIN_POSTGRES_SERVICE_HOST: andrew-django-admin-postgresql-1
    volumes:
      - type: bind
        source: .
        target: /var/andrew-django-admin
    ports:
      - 8080:8080
  postgresql:
    image: postgres:15.3-bookworm
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: andrew
      POSTGRES_DB: andrew
    ports:
      - 5432:5432
