# Generated by Django 4.2.3 on 2023-08-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="Title"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Subtitle"
                    ),
                ),
                (
                    "abstract",
                    models.TextField(blank=True, null=True, verbose_name="Abstract"),
                ),
                (
                    "cover_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cover_image/",
                        verbose_name="Cover image",
                    ),
                ),
                (
                    "parent_collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cms.collection",
                        verbose_name="Parent collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "git_repository",
                    models.CharField(max_length=200, verbose_name="Git repository"),
                ),
                ("filename", models.CharField(max_length=50, verbose_name="File name")),
                (
                    "group",
                    models.CharField(
                        choices=[("P", "Package"), ("T", "Tutorial")],
                        default="T",
                        max_length=1,
                        verbose_name="Type",
                    ),
                ),
                ("enable", models.BooleanField(default=True, verbose_name="Enable")),
                (
                    "collection",
                    models.ManyToManyField(
                        to="cms.collection", verbose_name="Collection"
                    ),
                ),
            ],
            options={
                "unique_together": {("git_repository", "filename")},
            },
        ),
    ]
