# Generated by Django 4.2.3 on 2023-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_repository', models.CharField(max_length=200)),
                ('file', models.CharField(max_length=50)),
            ],
        ),
    ]
