# Generated by Django 4.2.3 on 2023-07-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="content",
            unique_together={("git_repository", "file")},
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "title",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("abstract", models.TextField()),
                (
                    "parent_collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cms.collection",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="collection",
            field=models.ManyToManyField(to="cms.collection"),
        ),
    ]
