# Generated by Django 4.2.3 on 2023-07-24 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_alter_content_unique_together_collection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="parent_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cms.collection",
            ),
        ),
    ]
