# Generated by Django 4.2.3 on 2023-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_affiliation_author_content_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="orcid",
            field=models.CharField(max_length=19, unique=True, verbose_name="ORCID ID"),
        ),
    ]
