# Generated by Django 4.2.3 on 2023-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_alter_author_orcid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Website"),
        ),
    ]
