# Generated by Django 4.2.3 on 2023-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0006_content_enable"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Subtitle"
            ),
        ),
    ]
