# Generated by Django 4.2.3 on 2023-07-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_collection_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="cover_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cover_image/",
                verbose_name="Cover image",
            ),
        ),
    ]
