# Generated by Django 4.2.3 on 2023-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_collection_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="abstract",
            field=models.TextField(blank=True, null=True, verbose_name="Abstract"),
        ),
    ]
