# Generated by Django 4.2.3 on 2023-07-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_alter_collection_abstract"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="file",
            new_name="filename",
        ),
        migrations.AlterUniqueTogether(
            name="content",
            unique_together={("git_repository", "filename")},
        ),
    ]
