apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: check-for-postgres
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup ${ANDREW_DJANGO_ADMIN_POSTGRES_SERVICE_HOST}; do echo waiting for postgres; sleep 2; done"]
      containers:
        - name: {{ .Chart.Name }}
          image: gesiscss/{{ .Chart.Name }}:{{ .Chart.Version }}
          ports:
            - containerPort: 8080
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap
                  key: ALLOWED_HOSTS
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap
                  key: DJANGO_DEBUG
            - name: DJANGO_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap
                  key: DJANGO_LOG_LEVEL
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: django_secret_key
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-postgres
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-postgres
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-postgres
                  key: db
