apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv-volume-static
  labels:
    type: local
    content: static
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.host_static_files_dir | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pv-claim-static
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: local
      content: static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv-volume-media
  labels:
    type: local
    content: media
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.host_media_files_dir | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pv-claim-media
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      type: local
      content: media
