apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  ANDREW_HOST_NAME: {{ .Values.host | quote }}
  DJANGO_DEBUG: {{ .Values.debug | quote }}
  DJANGO_LOG_LEVEL: {{ .Values.log_level | quote }}
