apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres
  labels:
    app: {{ .Chart.Name }}-postgres
spec:
  selector:
    app: {{ .Chart.Name }}-postgres
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
