apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres
spec:
  selector:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
