apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-postgres
  labels:
    app: {{ .Chart.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: postgres:15.3-bookworm
          ports:
            - containerPort: 5432
          command: ["docker-entrypoint.sh"]
          args: ["-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-postgres
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-postgres
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-postgres
                  key: db
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: {{ .Chart.Name }}-postgres-pv-storage
            - name: {{ .Chart.Name }}-postgres-config
              mountPath: "/etc/postgresql"
              readOnly: true
      volumes:
        - name: {{ .Chart.Name }}-postgres-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-postgres-pv-claim
        - name: {{ .Chart.Name }}-postgres-config
          configMap:
            name: {{ .Chart.Name }}-postgres-configmap
